# Project: Bulls and cows
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Logo.o
LINKOBJ  = main.o Logo.o
LIBS     = -L"C:/Users/User/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -lbgi -lgdi32 -luser32 -std=c++11 -m32
INCS     = -I"C:/Users/User/Dev-Cpp/MinGW64/include" -I"C:/Users/User/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/User/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/User/Dev-Cpp/MinGW64/include" -I"C:/Users/User/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/User/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/User/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Bulls and cows.exe"
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Logo.o: Logo.cpp
	$(CPP) -c Logo.cpp -o Logo.o $(CXXFLAGS)
